name: fl_nodes
description: A lightweight, scalable, and highly customizable package that empowers Flutter developers to create dynamic, interactive, and visually appealing node-based UIs.
version: 0.3.0
maintainer: William Karol Di Cioccio

homepage: https://williamkaroldicioccio.github.io/fl_nodes/
repository: https://github.com/WilliamKarolDiCioccio/fl_nodes
issue_tracker: https://github.com/WilliamKarolDiCioccio/fl_nodes/issues
publish_to: 'none'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - visual-scripting
  - workflow-editor
  - node-editor

funding:
  - https://studio.buymeacoffee.com/dashboard

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_context_menu:
    path: ../flutter_context_menu
  flutter_shaders: ^0.1.3
  keymap: ^0.0.92
  os_detect: ^2.0.3
  uuid: ^4.5.1

dev_dependencies:
  melos: ^7.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

workspace:
  - examples/fl_nodes_example
  - examples/fl_context_menu_example
  - benchmarks
  - packages/fl_nodes
  - packages/fl_nodes_core
  - packages/fl_context_menu
  - packages/fl_nodes_visual_scripting
  - packages/fl_nodes_mind_maps

melos:
  publish:
    git:
      enabled: true

  command:
    bootstrap:
      runPubGetInParallel: true
      usePubspecOverrides: true
    version:
      linkToVersion: true
      updateDependents: true
      updateGitTagRefs: true

  scripts:
    format:
      run: melos exec -- "dart format ."
      description: Run dart format across all packages.

    analyze:
      run: melos exec -- "dart analyze --fatal-infos"
      description: Run dart analyze across all packages.

    example: cd examples/fl_nodes_example && flutter run -d chrome
    example:profile: cd examples/fl_nodes_example && flutter run --profile -d chrome
    example:release: cd examples/fl_nodes_example && flutter run --release -d chrome

flutter:
  uses-material-design: true
